dataset:
  clamp_im: true
  dataRoot: /home/disk1/Dataset/InteriorVerse
  imHeight: 512
  imWidth: 512
#   loader: folder
  num_workers: 1
  preload_level: 0
  shuffle: true
experiment:
  device_ids: [0, 1, 2, 3]
  id: material_prediction
  path_logs: ./exps/
  seed: 42
model: dense
optim:
  betas:
  - 0.5
  - 0.999
  lr: 0.00005
train:
  batch_size: 2
  epochs: 20
  perceptual:
    albedo:
    - 2
    material:
    - 2
    normal:
    - 2
    weight: 0.02
  save_epochs: 1
val:
  batch_size: 2
  interval: 1
